### PR TITLE
Provide option for cleaner/prettier links by removing .html suffix

### PR DESCRIPTION
**Pull request by florian-wagner**
Hi @leouieda,

this relatively small change allows to remove all `.html` suffixes from `{page}.html` by creating `{page}/index.html`. It can be activated by putting `link_style: pretty` in the config. Jekyll, Pelican and others have this feature and for me this provides a lot of benefits when not all the source files are named `index.md`.

This is a starting point and probably goes south when `{page}` exists as a folder alongside `{page}.md`. And it may also cause problems when using relative links, which I have not done yet, but I saw that you made this possible recently by a new jinja filter.

Let me know what you think.
Florian

### CODE REVIEW

**Comment by florian-wagner** [comment]
@leouieda I don't know why some checks fail. If I make black happy, then flake8 complains. Please advise.

**Comment by leouieda** [comment]
Hey @florian-wagner I managed to fix the incompatibility by using a function to check if the conditions. It's also easier to read that way so not a bad thing. I also changed the flag to `pretty_links: true` instead of `link_style` since this is basically the only one. I found a little issue when exporting notebook images and fixed that as well.

I tested it on my website and it works fine with relative links. The only problem is images inserted in the Markdown have to be specified with the pretty folder structure in mind since Nene won't be able to fix those. This is the part I don't particularly like about this setting versus putting everything in folders to begin with and so I probably won't be using this setting myself. But if that's something you're OK with then I don't mind.

The part about already having a folder is tricky but I think we can rely on people being sensible that if they turned this on then they need to be mindful of their directories.

**Comment by leouieda** [comment]
I'm dropping Python 3.6 support in #43 and will merge this in once that's passed.

**Comment by leouieda** [comment]
Merged!

**Pull request merged**
